=== andrius-butent/bee/war/WEB-INF/schemas/table.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.butent.com/table" elementFormDefault="qualified"
  xmlns="http://www.butent.com/table"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:type="http://www.butent.com/type">

  <xs:import namespace="http://www.butent.com/type" schemaLocation="types.xsd" />

  <xs:element name="BeeTable" type="table">
    <xs:unique name="uniqueFieldName">
      <xs:selector xpath=".//*" />
      <xs:field xpath="@name" />
    </xs:unique>
  </xs:element>

  <xs:complexType name="table">
    <xs:sequence>
      <xs:element name="BeeFields" type="fields" minOccurs="0" maxOccurs="1" />
      <xs:element name="BeeExtended" type="fields" minOccurs="0" maxOccurs="1" />
      <xs:element name="BeeStates" type="states" minOccurs="0" maxOccurs="1" />
      <xs:element name="BeeKeys" type="keys" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="name" type="type:tableNameType" use="required" />
    <xs:attribute name="idName" type="type:fieldNameType" default="ID" />
    <xs:attribute name="versionName" type="type:fieldNameType" default="VERSION" />
    <xs:attribute name="x" type="xs:int" />
    <xs:attribute name="y" type="xs:int" />
  </xs:complexType>

  <xs:complexType name="fields">
    <xs:sequence>
      <xs:element name="BeeField" type="fieldType" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="states">
    <xs:sequence>
      <xs:element name="BeeState" type="type:stateNameType" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="keys">
    <xs:sequence>
      <xs:element name="BeeKey" type="keyType" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="fieldType">
    <xs:attribute name="name" use="required" type="type:fieldNameType" />
    <xs:attribute name="type" type="type:dataType" use="required" />
    <xs:attribute name="precision" type="xs:integer" />
    <xs:attribute name="scale" type="xs:byte" />
    <xs:attribute name="notNull" type="xs:boolean" />
    <xs:attribute name="unique" type="xs:boolean" />
    <xs:attribute name="defExpr" type="defaultType" />          
    <xs:attribute name="defValue" type="type:notEmptyString" />          
    <xs:attribute name="relation" type="type:tableNameType" />
    <xs:attribute name="cascade" type="cascadeType" />
    <xs:attribute name="translatable" type="xs:boolean" />
  </xs:complexType>

  <xs:complexType name="keyType">
    <xs:sequence>
      <xs:element name="KeyField" type="type:fieldNameType" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="unique" type="xs:boolean" />
  </xs:complexType>

  <xs:simpleType name="cascadeType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="DELETE" />
      <xs:enumeration value="SET_NULL" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="defaultType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="CURRENT_DATE" />
      <xs:enumeration value="CURRENT_TIME" />
      <xs:enumeration value="CURRENT_USER" />
      <xs:enumeration value="NEXT_NUMBER" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== andrius-butent/bee/war/WEB-INF/config/modules/Calendar/tables/CalendarReminders.table.xml
<?xml version="1.0" encoding="UTF-8"?>
<BeeTable xmlns="http://www.butent.com/bee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.butent.com/bee ../../../../schemas/table.xsd"

  name="CalendarReminders"
  idName="CalendarReminderID"
  >
  <BeeFields>
    <BeeField name="Calendar" type="LONG" notNull="true" relation="Calendars" cascade="DELETE" />
    <BeeField name="ReminderType" type="LONG" notNull="true" relation="ReminderTypes" cascade="DELETE" />
    <BeeField name="Minutes" type="INTEGER" />
  </BeeFields>
  <BeeKeys>
    <BeeKey unique="true">
      <KeyField>Calendar</KeyField>
      <KeyField>ReminderType</KeyField>
    </BeeKey>
  </BeeKeys>
</BeeTable>

=== andrius-butent/bee/war/WEB-INF/config/tables/CompanyPersons.table.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<BeeTable xmlns="http://www.butent.com/bee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.butent.com/bee ../../schemas/table.xsd"
  
  name="CompanyPersons"
  idName="CompanyPersonID"
  x="501" y="339"
  >
  <BeeFields>
    <BeeField name="Company" type="LONG" notNull="true" relation="Companies" cascade="DELETE" />
    <BeeField name="Person" type="LONG" notNull="true" relation="Persons" cascade="DELETE" />
    <BeeField name="Position" type="STRING" precision="50" />
    <BeeField name="Contact" type="LONG" unique="true" relation="Contacts" />
  </BeeFields>
  <BeeKeys>
    <BeeKey unique="true">
      <KeyField>Company</KeyField>
      <KeyField>Person</KeyField>
    </BeeKey>
  </BeeKeys>
</BeeTable>
